name: Style
on: [push, pull_request]

jobs:
  Backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: 3.13
      - uses: astral-sh/setup-uv@v5
      - run: |
          make backend-lint
          make mypy

  Frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6.2.0
        with:
          node-version: 22
      - run: |
          npm i
          make front-lint
          
