database:
  user: user
  password: user
  host: "localhost:27017"
  name: engin33ring-thesis

long_term_storage:
  url: "http://localhost:9000"
  user: useruseruser
  password: useruseruser



logging:
  level: debug