database:
  user: user
  password: user
  host: "localhost:27017"
  name: engin33ring-thesis

long_term_storage:
  url: "http://localhost:9000"
  user: useruseruser
  password: useruseruser

authentication:
  secret: "e7637b17bd5d6f614a8bc5d9043e87e0cf62cf877495ceca86fdf2e160fd6e36"
  algorithm: HS256
  access_token_expire_mins: 30


logging:
  level: debug

otel:
  endpoint: "http://localhost:4318"

stitcher:
  temporary_dir: "/home/matiar/Programming/engin33ring-thesis/backend/resources/stitcher"
  bucket_name: "engin33ring-thesis-videos"